version: "3.8"

x-build: &default-build
  context: .
  dockerfile: Dockerfile.dev

services:
  rabbitmq:
    container_name: bpmn-engine-rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq:/etc/rabbitmq
    networks:
      - bpmn-net

  redis:
    container_name: bpmn-engine-redis
    image: 'redis:alpine'
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - bpmn-net

  db:
    container_name: bpmn-engine-db
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    networks:
      - bpmn-net

  app:
    container_name: bpmn_engine
    build: *default-build
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "${DJANGO_BIND_PORT}:${DJANGO_BIND_PORT}"
      - "5678:5678"
    depends_on:
      - db
      - redis
      - rabbitmq
    command:
      [
        "./scripts/wait-for-it.sh",
        "${DB_HOST}:${DB_PORT}",
        "-t",
        "120",
        "--",
        "./scripts/start.sh",
      ]
    networks:
      - bpmn-net
  
  worker:
    restart: always
    build: *default-build
    command: celery -A django_bpmn_engine worker -l INFO -Q run_workflow
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - rabbitmq
    networks:
      - bpmn-net

  beat:
    restart: always
    build: *default-build
    command: celery -A django_bpmn_engine beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - rabbitmq
      - db
    networks:
      - bpmn-net

networks:
  bpmn-net:
