version: "3.8"

x-build: &default-build
  context: .
  dockerfile: Dockerfile.dev

services:
  rabbitmq:
    container_name: bpmn-engine-rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    volumes:
      - ./rabbitmq:/etc/rabbitmq

  redis:
    container_name: bpmn-engine-redis
    image: 'redis:alpine'
    command: redis-server
    ports:
      - "6379:6379"

  db:
    container_name: bpmn-engine-db
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  app:
    container_name: bpmn_engine
    build: *default-build
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "${DJANGO_BIND_PORT}:${DJANGO_BIND_PORT}"
    depends_on:
      - db
      - redis
      - rabbitmq
    command:
      [
        "./scripts/wait-for-it.sh",
        "${DB_HOST}:${DB_PORT}",
        "-t",
        "120",
        "--",
        "./scripts/start.sh",
      ]
    networks:
      - default
