# Generated by Django 4.0 on 2022-09-19 22:52

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xml', models.TextField()),
                ('workflow_process_id', models.CharField(max_length=100)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED'), ('FAILURE', 'FAILURE')], db_index=True, default='RUNNING', max_length=20, verbose_name='State')),
                ('last_task', models.CharField(blank=True, max_length=100, null=True)),
                ('initial_data', models.JSONField(blank=True, default=dict, null=True)),
                ('root', models.UUIDField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workflowinstance')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.workflow')),
            ],
            options={
                'verbose_name': 'WorkflowInstance',
                'verbose_name_plural': 'WorkflowInstances',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTaskInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.UUIDField(blank=True, null=True)),
                ('children', models.JSONField(default=list)),
                ('last_state_change', models.DateTimeField()),
                ('state', models.PositiveSmallIntegerField(choices=[(4, 'FUTURE'), (8, 'WAITING'), (16, 'READY'), (64, 'CANCELLED'), (32, 'COMPLETED'), (2, 'LIKELY'), (1, 'MAYBE')])),
                ('task_spec', models.CharField(max_length=50)),
                ('triggered', models.BooleanField()),
                ('workflow_name', models.CharField(max_length=50)),
                ('internal_data', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.workflowinstance')),
            ],
            options={
                'verbose_name': 'WorkflowTaskInstance',
                'verbose_name_plural': 'WorkflowTaskInstances',
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(max_length=50)),
                ('input_data', models.JSONField(blank=True, default=dict, null=True)),
                ('form_fields', django_jsonform.models.fields.JSONField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict, null=True)),
                ('state', models.CharField(choices=[('NEW', 'NEW'), ('ASSIGNED', 'ASSIGNED'), ('COMPLETED', 'COMPLETED')], default='NEW', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='auth.user')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='core.workflowinstance')),
            ],
            options={
                'verbose_name': 'UserTask',
                'verbose_name_plural': 'UserTasks',
            },
        ),
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(max_length=50)),
                ('input_data', models.JSONField(blank=True, default=dict, null=True)),
                ('output_data', models.JSONField(blank=True, default=dict, null=True)),
                ('queue_name', models.CharField(max_length=50)),
                ('properties', models.JSONField(blank=True, default=dict, null=True)),
                ('state', models.CharField(choices=[('NEW', 'NEW'), ('ACTIVATED', 'ACTIVATED'), ('FAILURE', 'FAILURE'), ('COMPLETED', 'COMPLETED')], default='NEW', max_length=20)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tasks', to='core.workflowinstance')),
            ],
            options={
                'verbose_name': 'ServiceTask',
                'verbose_name_plural': 'ServiceTasks',
            },
        ),
        migrations.CreateModel(
            name='MessageTaskEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(max_length=50)),
                ('input_data', models.JSONField(blank=True, default=dict, null=True)),
                ('output_data', models.JSONField(blank=True, default=dict, null=True)),
                ('message_name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('WAITING', 'WAITING'), ('RECEIVED', 'RECEIVED')], default='WAITING', max_length=20)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_tasks', to='core.workflowinstance')),
            ],
            options={
                'verbose_name': 'MessageTaskEvent',
                'verbose_name_plural': 'MessageTaskEvents',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(max_length=50)),
                ('error', models.JSONField()),
                ('resolved', models.BooleanField(default=False)),
                ('input', models.JSONField(blank=True, default=dict, null=True)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.workflowinstance')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
            },
        ),
    ]
