# Generated by Django 4.0 on 2022-09-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='form_fields',
            field=models.JSONField(default=dict),
        ),
    ]
